### ISSUE TITLE
很赞的想法，怎么方便的添加数据？

### ISSUE THREAD

**Issue by iwillhappy1314** [putianxi/putianxi.github.io#1]
想法很赞，数据不全面，怎么方便的提交数据？是不是可以做个提交医院的表单？让大家来完善数据。

**Comment by putianxi** [comment]
目前没有做 CMS，只能是向 [hospital.csv](https://github.com/putianxi/putianxi.github.io/blob/master/assets/data/hospital.csv) 中添加数据，然后通过 [csv2geojson.py](https://github.com/putianxi/putianxi.github.io/blob/master/assets/script/csv2geojson.py) 生成新的 [hospital.geojson](https://github.com/putianxi/putianxi.github.io/blob/master/assets/data/hospital.geojson)，重新运行即可，如果网站访问量大的话，我会开发一个CMS 给大家提交数据，感谢您的支持

**Comment by wanghaisheng** [comment]
geo信息怎么查的 @putianxi
