### ISSUE TITLE
建议核实数据！

### ISSUE THREAD

**Issue by KeZhimin** [putianxi/putianxi.github.io#11]
建议核实数据，不然会给人带来困扰。。福建肿瘤医院怎么就变莆田系。。。如果是某个科室希望注明。这个数据是让人不要踩坑，但不希望因为这个数据让人错过最佳治疗时间。

**Comment by martianmartian** [comment]
就是啊，搞笑的，乱来嘛

**Comment by putianxi** [comment]
谢谢你的建议，已经移除
