### ISSUE TITLE
解放军第422医院也是莆田系的吗？

### ISSUE THREAD

**Issue by veeson** [putianxi/putianxi.github.io#16]
解放军第422医院是湛江的一所三甲医院，确定也是莆田系的吗？那家医院我去过，规模很大，算是很正规的。能否确认一下，谢谢。

**Comment by putianxi** [comment]
数据来源于这篇报道 [“莆田系”民营医院名单大揭秘](http://finance.china.com.cn/industry/medicine/disj/20160503/3705387.shtml)，可能是有部分科室属于莆田系承包，为了谨慎起见，暂时保留
