### ISSUE TITLE
很多三甲医院都被列为莆田系，建议检查一下数据源

### ISSUE THREAD

**Issue by hlleng** [putianxi/putianxi.github.io#24]
以重庆的数据为准：
1、新桥医院被列为莆田系，实则为三甲
![image](https://user-images.githubusercontent.com/4686802/71551616-40a68480-2a26-11ea-9870-758fc56f1e14.png)

2、解放军第324医院（解放军958医院）被列为莆田系，实则为三甲
![image](https://user-images.githubusercontent.com/4686802/71551625-6f245f80-2a26-11ea-8742-a0c2ddc12be9.png)

3、武警重庆总队医院被列为莆田系，实则为三甲
![image](https://user-images.githubusercontent.com/4686802/71551632-967b2c80-2a26-11ea-9f79-e5d54bb7fb1f.png)

数据来源：http://wsjkw.cq.gov.cn/getSanJiaYiYuan.jspx    重庆市卫生健康委员会

**Comment by whuailin** [comment]
可能是包了某个科室也算

**Comment by hlleng** [comment]
> 可能是包了某个科室也算

查了下，三甲医院不允许外包科室

**Comment by vadonmo** [comment]
> > 可能是包了某个科室也算
> 
> 查了下，三甲医院不允许外包科室

魏则西那个不就是三甲医院么

**Comment by doiyes** [comment]
> 
> 
> > 可能是包了某个科室也算
> 
> 查了下，三甲医院不允许外包科室

问题是国家卫生行政部门只能管普通三甲医院，不能管部队和武警后勤医院

**Comment by putianxi** [comment]
你说的这些部队医院，绝大部分都有科室被莆田系承包的状况，我没有办法核实每一个科室。这些数据均在 README 中有所说明，如果没有明确证据说这个医院不是，为了谨慎起见，我依然会标注，提醒大家小心。
