### ISSUE TITLE
有相关权威资料证实"北京宝岛妇产医院"是莆田系吗?

### ISSUE THREAD

**Issue by Huang-Libo** [putianxi/putianxi.github.io#6]
一直以为北京宝岛妇产医院是一个台资医院, 难道是莆田系?

**Comment by putianxi** [comment]
可以看这则报道

http://chinadigitaltimes.net/chinese/2016/05/%E6%99%BA%E8%B0%B7%E8%B6%8B%E5%8A%BF%EF%BD%9C%E8%8E%86%E7%94%B0%E7%B3%BB%E5%8C%BB%E9%99%A2%E6%AD%A3%E6%8A%8A%E6%89%8B%E4%BC%B8%E5%90%91%E4%B8%AD%E4%BA%A7/
