### ISSUE TITLE
点聚合的散开动画怎么实现的?

### ISSUE THREAD

**Issue by imac8t** [putianxi/putianxi.github.io#8]
诚心求教

**Comment by JiaXingKing** [comment]
leaflet里面有款插件，叫Cluster

**Comment by btredback** [comment]
openlayers也有Cluster聚合分析ol.source.Cluster

**Comment by putianxi** [comment]
使用的是 [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster) 插件
